apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: test-datasource
  namespace: grafana-operator
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: TestData DB
    type: testdata
    access: proxy
    isDefault: false
    editable: true

