apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana-operator
  labels:
    dashboards: "grafana"
spec:
  config:
    security:
      admin_user: admin
      admin_password: admin

